# screen_states: ["connect", "mm_sign", "main", "hunting", "heroes"]
# buttons_list: ["hero_drag_area", "bottom_work_button", "background_area", "hero_subpanel"]

# program timers; minutes
timers:
  refresh_timer: 5
  work_timer: 15
  check_timer: 3
  pause_timer: 1

# button center coordinates [x, y]
coords:
  hero_drag_area: [0.1401, 0.7290] #[620, 720]
  bottom_work_button: [0.4103, 0.7440] #[888, 730]
  background_area: [0.7319, 0.16168] #[1207, 341]
  hero_subpanel: [0.4950, 0.8862] #[972, 825]
  back_button: [0.05444, 0.05988] #[535, 273]
  connect_button: [0.5030, 0.7290] #[980, 720]
  mm_sign_button: [1.3498, 0.4746] # [1820, 550] # varies
  hunt_button: [0.5030, 0.4746] #[980, 550]
  new_map_button: [0.5030, 0.7290] #[980, 720]

# section locations as percentages of game screen area [x, y, w, h]
sections:
  connect: [0.3518, 0.6542, 0.2822, 0.1497]
  game: [0.0, 0.0, 1.0, 1.0]

# template files
files:
  connect: './templates/connect.png'
  mm: './templates/meta_sign.png'
  new_map: './templates/new_map.png'
  main: './templates/main.png'
  heroes: './templates/stamina_bar_green.png'
  tl_border_filename: './templates/top_left_border.png'
  br_border_filename: './templates/bottom_right_border.png'
